import Head from "next/head";
// import NewsletterSection from "../components/NewsletterSection";
import Products from "../components/Products";
import Products_title from "../components/Products_title";
import Products_title_blog from "../components/Products_title_blog";
import Slider_main from "../components/Slider_main";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider_main />
      <Products_title />
      <Products />

      {/* <NewsletterSection /> */}
      <Products_title_blog />
    </>
  );
}
